source 'http://rubygems.org'

gem 'rails'
gem 'gravatar_image_tag'
gem 'will_paginate'
gem 'sqlite3'
gem 'haml-rails'


group :development do
  gem 'rspec-rails'
  gem 'annotate'
  gem 'faker'
  gem 'hpricot'
  gem 'ruby_parser'

end

group :test do
  gem 'rspec-rails'
  gem 'webrat'
  gem 'spork'
  gem 'factory_girl_rails'
  #gem 'autotest'
  #gem 'autotest-rails-pure'
  #gem 'autotest-fsevent'
  #gem 'autotest-growl'
end